@startuml
'https://plantuml.com/object-diagram
' make a place for a description

' makes a place for the subtitle'
center header <font color=blue size=22>StoryBoard Diagrams</font>

folder "import diagram"{
    class webui
    class stablediffusion
    webui <- stablediffusion
    folder modules{
        folder storysquad_storyboard{
            class storyboard_gr
            class sb_rendering
            class sb_sd_rendering
            class storyboard
            class env
            storyboard_gr <-- sb_rendering
            storyboard_gr <-- sb_sd_rendering
            storyboard_gr <-- storyboard

            storyboard_gr <-- env
            storyboard <-- env
            sb_sd_rendering <-- env
            sb_rendering <-- env
            sb_rendering <-- storyboard

            webui <--- storyboard_gr
        }
    }
}
allowmixing
folder "data flow diagram"{
    class webui_
    class stablediffusion_
    webui_ <- stablediffusion_
    folder storysquad_storyboard_{
        class storyboard_gr_
        class sb_rendering_
        class sb_sd_rendering_
        class storyboard_
        class env_
        storyboard_gr_ <--> sb_rendering_
        storyboard_gr_ <--> sb_sd_rendering_
        storyboard_gr_ --> storyboard_

        storyboard_gr_ <-- env_
        storyboard_ <-- env_
        sb_sd_rendering_ <-- env_
        sb_rendering_ <-- env_
        sb_rendering_ <-- storyboard_

        webui_ <---> storyboard_gr_
        folder SB_RENDERS{
            class movie
            folder temp{
                 card tmp_frames
                 card tmp_movies
                 card tmp_audio
            }
        }
        sb_rendering_ --> movie
        sb_rendering_ --> temp
        sb_sd_rendering_ <--> sb_rendering_
    }
}

'storyboard_gr -- sb_rendering
'storyboard_gr -- sb_sd_rendering
'storyboard_gr -- storyboard

'modules -right-> cloned modules

@enduml
